name: CI

on:
  push:
    branches:
      - omp
  pull_request:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v2
            - name: Install dependencies
              run: |
                sudo apt-get -q update
                sudo apt-get -qy install libomp-dev libtbb-dev
                sudo apt-get -qy install \
                    curl build-essential make \
                    gcc g++ \
                    python3 python3-pip python3-pytest \
                    python3-numpy python3-scipy python3-pandas
                python3 -m pip install --upgrade pip
                pip install pytest pytest-cov pybind11
            - name: Test
              run: |
                make test
            - name: Demo Thread 1
              run: |
                make clean
                make demo OMP_THREAD_NUM=1
            - name: Demo Thread 2
              run: |
                make clean
                make demo OMP_THREAD_NUM=2
            - name: Demo Thread 4
              run: |
                make clean
                make demo OMP_THREAD_NUM=4
            - name: Demo Thread 8
              run: |
                make clean
                make demo OMP_THREAD_NUM=8
            - name: Demo Thread 16
              run: |
                make clean
                make demo OMP_THREAD_NUM=16