name: CI

on:
  push:
    branches:
      - dev_**
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
    build:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v2
            - name: list device info
              run: |
                lscpu
            - name: Install minimal prerequisites
              run: |
                sudo apt-get -q update
                sudo apt-get -qy install \
                    curl build-essential make \
                    gcc g++ \
                    python3 python3-pip python3-pytest
            - name: Install Python dependencies
              run: |
                python3 -m pip install --upgrade pip
                python3 -m pip install -r python/requirements.txt
            - name: Test
              run: |
                make test
                make demo